# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-06 10:47
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings

import shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, default=shortener.models.get_code)),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Number of Redirects')),
                ('target', models.PositiveSmallIntegerField(choices=settings.DEVICE_TYPES, default=settings.TYPE_DESKTOP))
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
    ]
