# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='target',
            field=models.CharField(choices=[(b'd', b'desktop'), (b'm', b'mobile'), (b't', b'tablet')], default=b'd', max_length=1),
        ),
    ]
